### ISSUE TITLE
Rebase 1.0 todo

### ISSUE THREAD

**Issue by NullNeska** [LLA-Gaming/LS13#1]
- [x] Port minor things (alpacas, brain's icons)
- [x] Port Cryotube Vision
- [x] Port Tablets
- [x] Port Perseus
- [x] port crew transfer vote
- [x] Setup database as NOTES require them ( @TheDracheX )
- [x] Solve minimap bug!! (VERY VITAL) (Apparently minimap bug is because guthen)
- [x] Fix guthen

Please comment with things to add to the list
Please comment only BUG FIXES and EXISTING FEATURES. nothing new.
